[database]
url = "sqlite:data/guloader.db?mode=rwc"
max_connections = 10

[storage]
base_path = "./downloads"
scans_path = "./scans"
max_size_gb = 50
compression = true
thumbnail_size = 200

[sites.tecno]
name = "Tecno Moon"
base_url = "https://tecno-moon.xyz"
scanner_type = "tecno"
downloader_type = "tecno"
rate_limit_ms = 1500
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.tecno.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = ".eph-num a"
image_container = ".reader-main"
image_url = ".reader-main img"
next_page = ".nav-next a"

[sites.eros]
name = "Eros Moon"
base_url = "https://eros-moon.xyz"
scanner_type = "eros"
downloader_type = "eros"
rate_limit_ms = 1500
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.eros.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = ".eph-num a"
image_container = ".reader-main"
image_url = ".reader-main img"
next_page = ".nav-next a"

[sites.madara]
name = "Madarascans"
base_url = "https://madarascans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.madara.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

[sites.thunder]
name = "Thunderscans"
base_url = "https://en-thunderscans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.thunder.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

[scanner]
interval_minutes = 10
max_concurrent_scans = 5
retry_attempts = 3
retry_delay_ms = 5000

[notifications]
discord_webhook = ""
telegram_bot_token = ""
telegram_chat_id = ""

[[manga]]
title = "The divine demon"
site = "eros"
url = "https://eros-moon.xyz/manga/the-divine-demons-grand-ascension/"
active = true

[[manga]]
title = "Worthless Profession Dragon Tamer"
site = "eros"
url = "https://eros-moon.xyz/manga/worthless-profession-dragon-tamer/"
active = true

[[manga]]
title = "Global Superpowers: Awakened with the Divine Zixiao Thunder"
site = "madara"
url = "https://madarascans.com/series/global-superpowers-awakened-with-the-divine-zixiao-thunder/"
active = true

[[manga]]
title = "Transmigrating Into the Cyber Game After Being on Top for Killing BOSS"
site = "thunder"
url = "https://en-thunderscans.com/comics/transmigrating-into-the-cyber-game-after-being-on-top-for-killing-boss/"
active = true

[[manga]]
title = "Chronicles of the Tang Sect"
site = "eros"
url = "https://eros-moon.xyz/manga/chronicles-of-the-tang-sect/"
active = true

[[manga]]
title = "Player Who Returned 10,000 Years Later"
site = "eros"
url = "https://eros-moon.xyz/manga/player-who-returned-10000-years-later/"
active = true

[[manga]]
title = "Daoist Master Wants to Ascend"
site = "eros"
url = "https://eros-moon.xyz/manga/daoist-master-wants-to-ascend/"
active = true

[[manga]]
title = "Childhood Friend of the Zenith"
site = "eros"
url = "https://eros-moon.xyz/manga/childhood-friend-of-the-zenith/"
active = true

[[manga]]
title = "Rebirth: Limitless System"
site = "eros"
url = "https://eros-moon.xyz/manga/rebirth-limitless-system/"
active = true

[[manga]]
title = "Unparalleled??? Rank Hidden Equipment"
site = "eros"
url = "https://eros-moon.xyz/manga/unparalleled-rank-hidden-equipment/"
active = true

[[manga]]
title = "Dumped By My Girlfriend, I Turned To Martial Arts"
site = "eros"
url = "https://eros-moon.xyz/manga/dumped-by-my-girlfriend-i-turned-to-martial-arts/"
active = true

[[manga]]
title = "The Regressed Son of a Duke is an Assassin"
site = "eros"
url = "https://eros-moon.xyz/manga/the-regressed-son-of-a-duke-is-an-assassin/"
active = true

[[manga]]
title = "Golden Core is a Star, and You Call This Cultivation?"
site = "eros"
url = "https://eros-moon.xyz/manga/golden-core-is-a-star-and-you-call-this-cultivation/"
active = true

[[manga]]
title = "The Great Mage Returns After 4000 Years"
site = "eros"
url = "https://eros-moon.xyz/manga/the-great-mage-returns-after-4000-years/"
active = true

[[manga]]
title = "Become a god in binary"
site = "eros"
url = "https://eros-moon.xyz/manga/become-a-god-in-binary/"
active = true

[[manga]]
title = "Emperor of Solo Play"
site = "eros"
url = "https://eros-moon.xyz/manga/emperor-of-solo-play/"
active = true

[[manga]]
title = "Eternally Regressing Knight"
site = "eros"
url = "https://eros-moon.xyz/manga/eternally-regressing-knight/"
active = true

[[manga]]
title = "Revenge of the Iron-Blooded Sword Hound"
site = "eros"
url = "https://eros-moon.xyz/manga/revenge-of-the-iron-blooded-sword-hound/"
active = true

[[manga]]
title = "My Ruined Academy Life"
site = "eros"
url = "https://eros-moon.xyz/manga/my-ruined-academy-life/"
active = true

[[manga]]
title = "Soulblade Warrior"
site = "eros"
url = "https://eros-moon.xyz/manga/soulblade-warrior/"
active = true

[[manga]]
title = "Aristocrat’s Revenge"
site = "eros"
url = "https://eros-moon.xyz/manga/aristocrats-revenge/"
active = true

[[manga]]
title = "The 31st Piece Overturns the Board"
site = "eros"
url = "https://eros-moon.xyz/manga/the-31st-piece-overturns-the-board/"
active = true

[[manga]]
title = "Calamity Leveling"
site = "eros"
url = "https://eros-moon.xyz/manga/calamity-leveling/"
active = true

[[manga]]
title = "Player Elimination Project!"
site = "eros"
url = "https://eros-moon.xyz/manga/player-elimination-project/"
active = true

[[manga]]
title = "I Will Raise This Family to Greatness"
site = "eros"
url = "https://eros-moon.xyz/manga/i-will-raise-this-family-to-greatness/"
active = true

[[manga]]
title = "Virus King"
site = "eros"
url = "https://eros-moon.xyz/manga/virus-king/"
active = true

[[manga]]
title = "The Genius of Magical Mastery"
site = "eros"
url = "https://eros-moon.xyz/manga/the-genius-of-magical-mastery/"
active = true

[[manga]]
title = "Monopolizing Fortunes"
site = "eros"
url = "https://eros-moon.xyz/manga/monopolizing-fortunes/"
active = true

[[manga]]
title = "Murim’s Youngest Miracle Demon Doctor"
site = "eros"
url = "https://eros-moon.xyz/manga/murims-youngest-miracle-demon-doctor/"
active = true

[[manga]]
title = "I Became The Villain The Hero Is Obsessed With"
site = "madara"
url = "https://madarascans.com/series/i-became-the-villain-the-hero-is-obsessed-with/"
active = true

[[manga]]
title = "My Disciples Are All Big Villains"
site = "madara"
url = "https://madarascans.com/series/my-disciples-are-all-big-villains/"
active = true

[[manga]]
title = "I Became a Swordsmanship Instructor at the Academy"
site = "madara"
url = "https://madarascans.com/series/the-academys-new-swordmaster/"
active = true

[[manga]]
title = "People Actually Think Cultivation Is Hard?"
site = "madara"
url = "https://madarascans.com/series/people-actually-think-cultivation-is-hard/"
active = true

[[manga]]
title = "The Yellow-Haired Villain in the Female Main Character’s Novel Wants Happiness"
site = "madara"
url = "https://madarascans.com/series/the-yellow-haired-villain-in-the-female-main-characters-novel-wants-happiness/"
active = true

[[manga]]
title = "Secret Family"
site = "madara"
url = "https://madarascans.com/series/secret-family/"
active = true

[[manga]]
title = "Fighting Uncle"
site = "madara"
url = "https://madarascans.com/series/fighting-uncle/"
active = true

[[manga]]
title = "Infinite Awakening"
site = "madara"
url = "https://madarascans.com/series/infinite-awakening/"
active = true

[[manga]]
title = "The Genius Midfielder’s Passes are Special"
site = "madara"
url = "https://madarascans.com/series/the-genius-midfielders-passes-are-special/"
active = true

[[manga]]
title = "After being laid off, I got hundreds of millions of systems, and I upgraded them alone"
site = "madara"
url = "https://madarascans.com/series/after-being-laid-off-i-got-hundreds-of-millions-of-systems-and-i-upgraded-them-alone/"
active = true

[[manga]]
title = "Axe God: The Invincible Road"
site = "madara"
url = "https://madarascans.com/series/axe-god-the-invincible-road/"
active = true

[[manga]]
title = "0th correctional officer"
site = "madara"
url = "https://madarascans.com/series/0th-correctional-officer/"
active = true

[[manga]]
title = "Trillions of Resources in Apocalypse"
site = "madara"
url = "https://madarascans.com/series/trillions-of-resources-in-apocalypse/"
active = true

[[manga]]
title = "From Rural Instructor to Sword Saint"
site = "madara"
url = "https://madarascans.com/series/from-rural-instructor-to-sword-saint/"
active = true

[[manga]]
title = "Divine Ring Descends: The Strongest Otherworld"
site = "thunder"
url = "https://en-thunderscans.com/comics/divine-ring-descends-the-strongest-otherworld/"
active = true

[[manga]]
title = "Magic Level 99990000 All-Attribute Great Sage"
site = "thunder"
url = "https://en-thunderscans.com/comics/magic-level-99990000-all-attribute-great-sage/"
active = true

[[manga]]
title = "I Got The Weakest Class, Dragon Tamer!?"
site = "thunder"
url = "https://en-thunderscans.com/comics/0086250808-i-got-the-weakest-class-dragon-tamer/"
active = true

[[manga]]
title = "Demonic Emperor"
site = "thunder"
url = "https://en-thunderscans.com/comics/demonic-emperor/"
active = true

[[manga]]
title = "My Dad Is Too Strong"
site = "thunder"
url = "https://en-thunderscans.com/comics/my-dad-is-too-strong/"
active = true

[[manga]]
title = "I Was More Overpowered Than the Hero So I Held My Power"
site = "thunder"
url = "https://en-thunderscans.com/comics/i-was-more-overpowered-than-the-hero-so-i-held-my-power/"
active = true

[[manga]]
title = "I Shall Seal the Heavens"
site = "thunder"
url = "https://en-thunderscans.com/comics/i-shall-seal-the-heavens/"
active = true

[[manga]]
title = "The Genius Blacksmith’s Game"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-genius-blacksmiths-game/"
active = true

[[manga]]
title = "The Great Heavenly Demon Sovereign"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-great-heavenly-demon-sovereign/"
active = true

[[manga]]
title = "The Last Rebel: The Savior Android Levels Up to Change the Future"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-last-rebel-the-savior-android-levels-up-to-change-the-future/"
active = true

[[manga]]
title = "Becoming a God in the Binary World"
site = "thunder"
url = "https://en-thunderscans.com/comics/becoming-a-god-in-the-binary-world/"
active = true

[[manga]]
title = "Curse of the Vengeful Tongue"
site = "thunder"
url = "https://en-thunderscans.com/comics/curse-of-the-vengeful-tongue/"
active = true

[[manga]]
title = "The Youngest Son of the Eunhae Merchant Group"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-youngest-son-of-the-eunhae-merchant-group/"
active = true

[[manga]]
title = "Savior of Divine Blood ~Draw Out 0.00000001% To Become the Strongest~"
site = "thunder"
url = "https://en-thunderscans.com/comics/savior-of-divine-blood-draw-out-0-00000001-to-become-the-strongest/"
active = true

[[manga]]
title = "The Guided Adventurer: Fast-Route to Becoming the Strongest"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-guided-adventurer-fast-route-to-becoming-the-strongest/"
active = true

[[manga]]
title = "Tyrant of the Otherworld: My Shadow Can Evolve Infinitely"
site = "thunder"
url = "https://en-thunderscans.com/comics/tyrant-of-the-otherworld-my-shadow-can-evolve-infinitely/"
active = true

[[manga]]
title = "The Thousand-Faced Actor"
site = "thunder"
url = "https://en-thunderscans.com/comics/the-thousand-faced-actor/"
active = true

[[manga]]
title = "A Mountain of Corpses, A Sea of Blood"
site = "thunder"
url = "https://en-thunderscans.com/comics/a-mountain-of-corpses-a-sea-of-blood/"
active = true

[[manga]]
title = "Memoir of the God of War"
site = "thunder"
url = "https://en-thunderscans.com/comics/memoir-of-the-god-of-war/"
active = true

[[manga]]
title = "Solo Conqueror of the Chaotic World"
site = "thunder"
url = "https://en-thunderscans.com/comics/solo-conqueror-of-the-chaotic-world/"
active = true

[[manga]]
title = "The Tutorial is Too Hard"
site = "tecno"
url = "https://tecno-moon.xyz/manga/the-tutorial-is-too-hard/"
active = true

[[manga]]
title = "Childhood Friend of the Zenith"
site = "tecno"
url = "https://tecno-moon.xyz/manga/childhood-friend-of-the-zenith/"
active = true

[[manga]]
title = "Others level up, I cultivate—emerging only at Great Ascension"
site = "tecno"
url = "https://tecno-moon.xyz/manga/others-level-up-i-cultivate-emerging-only-at-great-ascension/"
active = true

[[manga]]
title = "I Shall Seal the Heavens"
site = "tecno"
url = "https://tecno-moon.xyz/manga/i-shall-seal-the-heavens/"
active = true

[[manga]]
title = "I, the creator of the evil god"
site = "tecno"
url = "https://tecno-moon.xyz/manga/i-the-creator-of-the-evil-god/"
active = true

[[manga]]
title = "I alone cut down the chaotic world"
site = "tecno"
url = "https://tecno-moon.xyz/manga/i-alone-cut-down-the-chaotic-world/"
active = true

[[manga]]
title = "Never mess with Senior Brother"
site = "tecno"
url = "https://tecno-moon.xyz/manga/never-mess-with-senior-brother/"
active = true

[[manga]]
title = "Beast Evolution"
site = "tecno"
url = "https://tecno-moon.xyz/manga/beast-evolution/"
active = true

[[manga]]
title = "From the womb to dominance: Unbeatable at birth"
site = "tecno"
url = "https://tecno-moon.xyz/manga/from-the-womb-to-dominance-unbeatable-at-birth/"
active = true

[[manga]]
title = "Eternally Regressing Knight"
site = "tecno"
url = "https://tecno-moon.xyz/manga/eternally-regressing-knight/"
active = true

[[manga]]
title = "The Great Mage Returns After 4000 Years"
site = "tecno"
url = "https://tecno-moon.xyz/manga/the-great-mage-returns-after-4000-years/"
active = true

[[manga]]
title = "Revenge of the Iron-Blooded Sword Hound"
site = "tecno"
url = "https://tecno-moon.xyz/manga/revenge-of-the-iron-blooded-sword-hound-2/"
active = true

[[manga]]
title = "Evolution Begins With A Big Tree"
site = "tecno"
url = "https://tecno-moon.xyz/manga/evolution-begins-with-a-big-tree/"
active = true

[[manga]]
title = "Magic Emperor"
site = "tecno"
url = "https://tecno-moon.xyz/manga/magic-emperor/"
active = true

[[manga]]
title = "Solo Bug Player"
site = "tecno"
url = "https://tecno-moon.xyz/manga/solo-bug-player/"
active = true

[[manga]]
title = "The Genius Midfielder’s Pass Is Special"
site = "tecno"
url = "https://tecno-moon.xyz/manga/the-genius-midfielders-pass-is-special/"
active = true

[[manga]]
title = "System Creator: Reborn to Stop the Apocalypse"
site = "tecno"
url = "https://tecno-moon.xyz/manga/system-creator-reborn-to-stop-the-apocalypse/"
active = true

[[manga]]
title = "Reincarnated as an Abandoned Baby Princess"
site = "tecno"
url = "https://tecno-moon.xyz/manga/reincarnated-as-an-abandoned-baby-princess/"
active = true

[[manga]]
title = "Trash of the Count’s Family"
site = "tecno"
url = "https://tecno-moon.xyz/manga/trash-of-the-counts-family/"
active = true

[[manga]]
title = "Magic Academy’s Genius Blinker"
site = "tecno"
url = "https://tecno-moon.xyz/manga/magic-academys-genius-blinker/"
active = true

[[manga]]
title = "Swordmaster’s Youngest Son"
site = "tecno"
url = "https://tecno-moon.xyz/manga/swordmasters-youngest-son-2/"
active = true

[[manga]]
title = "Reborn Ranker – Gravity User"
site = "tecno"
url = "https://tecno-moon.xyz/manga/reborn-ranker-gravity-user/"
active = true

[[manga]]
title = "Overgeared"
site = "tecno"
url = "https://tecno-moon.xyz/manga/overgeared/"
active = true

[[manga]]
title = "Standard of Reincarnation"
site = "tecno"
url = "https://tecno-moon.xyz/manga/standard-of-reincarnation/"
active = true

[[manga]]
title = "Dungeon Odyssey"
site = "tecno"
url = "https://tecno-moon.xyz/manga/dungeon-odyssey/"
active = true

[[manga]]
title = "My Lucky Encounter From The Game Turned Into Reality"
site = "tecno"
url = "https://tecno-moon.xyz/manga/my-lucky-encounter-from-the-game-turned-into-reality-2/"
active = true

[[manga]]
title = "After Transmigrating into the Cyberpunk Game, I Defeated the BOSS and Successfully Rose to the Top"
site = "eros"
url = "https://eros-moon.xyz/manga/after-transmigrating-into-the-cyberpunk-game-i-defeated-the-boss-and-successfully-rose-to-the-top/"
active = true
