[database]
url = "sqlite:data/guloader.db?mode=rwc"
max_connections = 10

[storage]
base_path = "./downloads"
scans_path = "./scans"
max_size_gb = 50
compression = true
thumbnail_size = 200

[sites.thunder]
name = "Thunderscans"
base_url = "https://thunderscans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.thunder.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

[sites.eros]
name = "Eros Moon"
base_url = "https://eros-moon.xyz"
scanner_type = "eros"
downloader_type = "eros"
rate_limit_ms = 1500
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.eros.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = ".eph-num a"
image_container = ".reader-main"
image_url = ".reader-main img"
next_page = ".nav-next a"

[sites.madara]
name = "Madarascans"
base_url = "https://madarascans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.madara.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

[scanner]
interval_minutes = 10
max_concurrent_scans = 5
retry_attempts = 3
retry_delay_ms = 5000

[notifications]
discord_webhook = ""
telegram_bot_token = ""
telegram_chat_id = ""

[[manga]]
title = "The divine demon"
site = "eros"
url = "https://eros-moon.xyz/manga/the-divine-demons-grand-ascension/"
active = true

[[manga]]
title = "Worthless Profession Dragon Tamer"
site = "eros"
url = "https://eros-moon.xyz/manga/worthless-profession-dragon-tamer/"
active = true

[[manga]]
title = "Global Superpowers: Awakened with the Divine Zixiao Thunder"
site = "madara"
url = "https://madarascans.com/series/global-superpowers-awakened-with-the-divine-zixiao-thunder/"
active = true

[[manga]]
title = "Transmigrating Into the Cyber Game After Being on Top for Killing BOSS"
site = "thunder"
url = "https://en-thunderscans.com/comics/transmigrating-into-the-cyber-game-after-being-on-top-for-killing-boss/"
active = true

[[manga]]
title = "Chronicles of the Tang Sect"
site = "eros"
url = "https://eros-moon.xyz/manga/chronicles-of-the-tang-sect/"
active = true

[[manga]]
title = "Player Who Returned 10,000 Years Later"
site = "eros"
url = "https://eros-moon.xyz/manga/player-who-returned-10000-years-later/"
active = true

[[manga]]
title = "Daoist Master Wants to Ascend"
site = "eros"
url = "https://eros-moon.xyz/manga/daoist-master-wants-to-ascend/"
active = true

[[manga]]
title = "Childhood Friend of the Zenith"
site = "eros"
url = "https://eros-moon.xyz/manga/childhood-friend-of-the-zenith/"
active = true

[[manga]]
title = "Rebirth: Limitless System"
site = "eros"
url = "https://eros-moon.xyz/manga/rebirth-limitless-system/"
active = true

[[manga]]
title = "Unparalleled??? Rank Hidden Equipment"
site = "eros"
url = "https://eros-moon.xyz/manga/unparalleled-rank-hidden-equipment/"
active = true

[[manga]]
title = "Dumped By My Girlfriend, I Turned To Martial Arts"
site = "eros"
url = "https://eros-moon.xyz/manga/dumped-by-my-girlfriend-i-turned-to-martial-arts/"
active = true

[[manga]]
title = "The Regressed Son of a Duke is an Assassin"
site = "eros"
url = "https://eros-moon.xyz/manga/the-regressed-son-of-a-duke-is-an-assassin/"
active = true

[[manga]]
title = "Golden Core is a Star, and You Call This Cultivation?"
site = "eros"
url = "https://eros-moon.xyz/manga/golden-core-is-a-star-and-you-call-this-cultivation/"
active = true

[[manga]]
title = "The Great Mage Returns After 4000 Years"
site = "eros"
url = "https://eros-moon.xyz/manga/the-great-mage-returns-after-4000-years/"
active = true

[[manga]]
title = "Become a god in binary"
site = "eros"
url = "https://eros-moon.xyz/manga/become-a-god-in-binary/"
active = true

[[manga]]
title = "Emperor of Solo Play"
site = "eros"
url = "https://eros-moon.xyz/manga/emperor-of-solo-play/"
active = true

[[manga]]
title = "Eternally Regressing Knight"
site = "eros"
url = "https://eros-moon.xyz/manga/eternally-regressing-knight/"
active = true

[[manga]]
title = "Revenge of the Iron-Blooded Sword Hound"
site = "eros"
url = "https://eros-moon.xyz/manga/revenge-of-the-iron-blooded-sword-hound/"
active = true

[[manga]]
title = "My Ruined Academy Life"
site = "eros"
url = "https://eros-moon.xyz/manga/my-ruined-academy-life/"
active = true

[[manga]]
title = "Soulblade Warrior"
site = "eros"
url = "https://eros-moon.xyz/manga/soulblade-warrior/"
active = true

[[manga]]
title = "Aristocrat’s Revenge"
site = "eros"
url = "https://eros-moon.xyz/manga/aristocrats-revenge/"
active = true

[[manga]]
title = "The 31st Piece Overturns the Board"
site = "eros"
url = "https://eros-moon.xyz/manga/the-31st-piece-overturns-the-board/"
active = true

[[manga]]
title = "Calamity Leveling"
site = "eros"
url = "https://eros-moon.xyz/manga/calamity-leveling/"
active = true

[[manga]]
title = "Player Elimination Project!"
site = "eros"
url = "https://eros-moon.xyz/manga/player-elimination-project/"
active = true

[[manga]]
title = "I Will Raise This Family to Greatness"
site = "eros"
url = "https://eros-moon.xyz/manga/i-will-raise-this-family-to-greatness/"
active = true

[[manga]]
title = "Virus King"
site = "eros"
url = "https://eros-moon.xyz/manga/virus-king/"
active = true

[[manga]]
title = "The Genius of Magical Mastery"
site = "eros"
url = "https://eros-moon.xyz/manga/the-genius-of-magical-mastery/"
active = true

[[manga]]
title = "Monopolizing Fortunes"
site = "eros"
url = "https://eros-moon.xyz/manga/monopolizing-fortunes/"
active = true

[[manga]]
title = "Murim’s Youngest Miracle Demon Doctor"
site = "eros"
url = "https://eros-moon.xyz/manga/murims-youngest-miracle-demon-doctor/"
active = true
