# GuLoader Configuration

[database]
url = "sqlite:data/guloader.db?mode=rwc"
max_connections = 10

[storage]
base_path = "./downloads"
scans_path = "./scans"
max_size_gb = 50
compression = true
thumbnail_size = 200

[scanner]
interval_minutes = 10
max_concurrent_scans = 5
retry_attempts = 3
retry_delay_ms = 5000

[notifications]
discord_webhook = ""
telegram_bot_token = ""
telegram_chat_id = ""

# Site configurations
[sites.eros]
name = "Eros Moon"
base_url = "https://eros-moon.xyz"
scanner_type = "eros"
downloader_type = "eros"
rate_limit_ms = 1500
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.eros.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = ".eph-num a"
image_container = ".reader-main"
image_url = ".reader-main img"
next_page = ".nav-next a"

[sites.madara]
name = "Madarascans"
base_url = "https://madarascans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.madara.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

[sites.thunder]
name = "Thunderscans"
base_url = "https://thunderscans.com"
scanner_type = "madara"
downloader_type = "madara"
rate_limit_ms = 1000
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[sites.thunder.selectors]
manga_list = ".story_item"
chapter_list = "#chapterlist li"
chapter_title = ".chapternum"
chapter_url = "a"
image_container = ".reading-content"
image_url = ".reading-content img"
next_page = ".nav-next a"

# Example manga to monitor
# Add your manga URLs here
[[manga]]
title = "The divine demon"
site = "eros"
url = "https://eros-moon.xyz/manga/the-divine-demons-grand-ascension/"
active = true

[[manga]]
title = "Worthless Profession Dragon Tamer"
site = "eros"
url = "https://eros-moon.xyz/manga/worthless-profession-dragon-tamer/"
active = true

[[manga]]
title = "Global Superpowers: Awakened with the Divine Zixiao Thunder"
site = "madara"
url = "https://madarascans.com/series/global-superpowers-awakened-with-the-divine-zixiao-thunder/"
active = true

[[manga]]
title = "Transmigrating Into the Cyber Game After Being on Top for Killing BOSS"
site = "thunder"
url = "https://en-thunderscans.com/comics/transmigrating-into-the-cyber-game-after-being-on-top-for-killing-boss/"
active = true
