name: Manga Monitor

on:
  schedule:
    # Мониторинг каждые 3 минуты, но только 10 манг за раз
    - cron: '*/3 * * * *'
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches: [ '**' ]
    # Без paths: запускать на любой измененный файл в любой ветке

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Clean up disk space
      run: |
        # Агрессивная очистка диска перед началом
        sudo rm -rf /tmp/*
        sudo rm -rf ~/.cargo/registry/cache/*
        sudo rm -rf /var/cache/*
        sudo rm -rf /var/log/*
        sudo apt-get clean
        sudo apt-get autoclean
        df -h
        
    - name: Build guloader
      run: cargo build --release
    
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory "${{ github.workspace }}"
        git config --local pull.rebase true
        git config --local rebase.autoStash true
    
    - name: Run manga monitoring (5-min, limited load)
      run: |
        # Создаем директории если их нет
        mkdir -p data downloads scans
        
        # Инициализируем базу данных если её нет
        if [ ! -f "data/guloader.db" ]; then
          echo "Initializing database..."
          ./target/release/guloader --config config.toml init
        fi
        
        # Запускаем мониторинг с ограниченной нагрузкой
        echo "Starting manga monitoring (every 3 min, limit 10 chapter downloads)..."
        echo "Will scan ALL manga, but download at most 10 chapters..."
        
        # Сканируем всех, но ограничиваем СКАЧИВАНИЯ глав числом 10
        ./target/release/guloader --config config.toml monitor --auto-commit --limit 10
        
        # Показываем статус после мониторинга
        echo "Monitoring completed. Showing status..."
        ./target/release/guloader --config config.toml status
        
        # Очищаем только временные файлы, НЕ удаляем downloads/
        echo "Cleaning up temporary files..."
        find data/ -name "*.db-journal" -delete 2>/dev/null || true
        find scans/ -type f -mtime +1 -delete 2>/dev/null || true
        # НЕ удаляем downloads/ - они должны сохраняться!
        
        # Дополнительная очистка системных файлов
        sudo rm -rf /tmp/*
        sudo rm -rf ~/.cargo/registry/cache/*
        df -h
    
    - name: Commit changes
      run: |
        # Проверяем есть ли изменения
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git add .
          
          # Создаем информативное сообщение коммита
          COMMIT_MSG="🤖 Auto-update: $(date '+%Y-%m-%d %H:%M:%S UTC')\n\n$(git status --porcelain | head -20)\nRun ID: ${{ github.run_id }}"
          
          git commit -m "$COMMIT_MSG"
          # Обновляем локальную ветку перед пушем, чтобы избежать расхождений
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push origin "HEAD:${GITHUB_REF_NAME}"
          echo "Changes committed successfully"
        else
          echo "No changes to commit"
        fi
    
    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          data/
          *.log