name: Manga Monitor

on:
  schedule:
    # Мониторинг (каждые 5 минут)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches: [ '**' ]
    # Без paths: запускать на любой измененный файл в любой ветке

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build guloader
      run: cargo build --release
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Run manga monitoring (5-min)
      run: |
        # Создаем директории если их нет
        mkdir -p data downloads scans
        
        # Инициализируем базу данных если её нет
        if [ ! -f "data/guloader.db" ]; then
          echo "Initializing database..."
          ./target/release/guloader --config config.toml init
        fi
        
        # Запускаем мониторинг
        echo "Starting manga monitoring (5-min)..."
        ./target/release/guloader --config config.toml monitor --auto-commit
        
        # Показываем статус после мониторинга
        echo "Monitoring completed. Showing status..."
        ./target/release/guloader --config config.toml status
    
    - name: Commit changes
      run: |
        # Проверяем есть ли изменения
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git add .
          
          # Создаем информативное сообщение коммита
          COMMIT_MSG="🤖 Auto-update: $(date '+%Y-%m-%d %H:%M:%S UTC')
          
          Changes detected:
          $(git status --porcelain | head -10)
          
          Run ID: ${{ github.run_id }}"
          
          git commit -m "$COMMIT_MSG"
          git push
          echo "Changes committed successfully"
        else
          echo "No changes to commit"
        fi
    
    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          data/
          *.log