name: Manga Catalog Full Check

on:
  schedule:
    # Каждые 10 часов (0:00, 10:00, 20:00)
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Clean up disk space
      run: |
        # Очищаем старые файлы перед началом
        sudo rm -rf /tmp/*
        sudo rm -rf ~/.cargo/registry/cache/*
        df -h

    - name: Build
      run: cargo build --release

    - name: Run full catalog check (every 10 hours)
      run: |
        mkdir -p data downloads scans

        if [ ! -f "data/guloader.db" ]; then
          echo "Initializing database..."
          ./target/release/guloader --config config.toml init
        fi

        echo "Starting 10-hour catalog check cycle..."
        echo "Processing 50 manga per 20-minute batch..."
        
        # Полная проверка: все сайты, скачать все главы и записать в конфиг
        # Ограничиваем нагрузку: обрабатываем по 50 манг за раз
        ./target/release/guloader --config config.toml check all -d --cfg --limit 50
        
        echo "Catalog check cycle completed. Waiting 20 minutes before next batch..."
        sleep 1200  # 20 минут
        
        # Повторяем еще один цикл для распределения нагрузки
        echo "Starting second batch..."
        ./target/release/guloader --config config.toml check all -d --cfg --limit 50
        
        # Очищаем только временные файлы, НЕ удаляем downloads/
        echo "Cleaning up temporary files..."
        find data/ -name "*.db-journal" -delete 2>/dev/null || true
        find scans/ -type f -mtime +1 -delete 2>/dev/null || true
        # НЕ удаляем downloads/ - они должны сохраняться!
        df -h

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory "${{ github.workspace }}"
        git config --local pull.rebase true
        git config --local rebase.autoStash true
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          COMMIT_MSG="🤖 Почасовая проверка каталога: $(date '+%Y-%m-%d %H:%M:%S UTC')\n\n$(git status --porcelain | head -20)\nRun ID: ${{ github.run_id }}"
          git commit -m "$COMMIT_MSG"
          # Обновляем удалённую ветку, избегая расхождений
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push origin "HEAD:${GITHUB_REF_NAME}"
        else
          echo "No changes to commit"
        fi


