name: Manga Catalog Full Check

on:
  schedule:
    # Каждые 30 минут
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    # Отключаем кэш cargo чтобы сэкономить место на диске
    # - name: Cache cargo
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Clean up disk space (aggressive)
      run: |
        # Максимально агрессивная очистка диска
        sudo rm -rf /tmp/*
        sudo rm -rf ~/.cargo/registry/cache/*
        sudo rm -rf ~/.cargo/registry/src/*
        sudo rm -rf ~/.cargo/git/db/*
        sudo rm -rf /var/cache/*
        sudo rm -rf /var/log/*
        sudo rm -rf /home/runner/.cache/*
        sudo rm -rf /usr/share/doc/*
        sudo rm -rf /usr/share/man/*
        sudo rm -rf /usr/share/locale/*
        sudo rm -rf /usr/share/info/*
        sudo apt-get clean
        sudo apt-get autoclean
        sudo apt-get autoremove -y
        # Очищаем ВСЕ скачанные файлы чтобы освободить максимум места
        rm -rf downloads/* 2>/dev/null || true
        rm -rf scans/* 2>/dev/null || true
        # Очищаем кэш cargo полностью
        rm -rf ~/.cargo/registry/cache/* 2>/dev/null || true
        rm -rf ~/.cargo/git/db/* 2>/dev/null || true
        df -h

    - name: Build (optimized for space)
      run: |
        # Очищаем target перед сборкой
        rm -rf target/
        # Сборка с оптимизацией для экономии места
        cargo build --release --offline || cargo build --release

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory "${{ github.workspace }}"
        git config --local pull.rebase true
        git config --local rebase.autoStash true

    - name: Run full catalog check (every 30 minutes)
      run: |
        mkdir -p data downloads scans

        if [ ! -f "data/guloader.db" ]; then
          echo "Initializing database..."
          ./target/release/guloader --config config.toml init
        fi

        echo "Starting 30-minute catalog check cycle..."
        echo "Limit: 20 chapter downloads per batch (catalog scan is full)"
        
        # Полная проверка: сканируем каталог полностью, но ограничиваем СКАЧИВАНИЯ глав до 20
        ./target/release/guloader --config config.toml check all -d --cfg --limit 20
        
        # Показываем статус после проверки каталога
        echo "Catalog check completed. Showing status..."
        ./target/release/guloader --config config.toml status
        
        # Максимальная очистка после выполнения
        echo "Cleaning up all temporary files..."
        find data/ -name "*.db-journal" -delete 2>/dev/null || true
        # Удаляем ВСЕ скачанные файлы чтобы освободить максимум места
        rm -rf downloads/* 2>/dev/null || true
        rm -rf scans/* 2>/dev/null || true
        # Удаляем target чтобы освободить место
        rm -rf target/ 2>/dev/null || true
        
        # Дополнительная очистка системных файлов
        sudo rm -rf /tmp/*
        sudo rm -rf ~/.cargo/registry/cache/*
        sudo rm -rf ~/.cargo/git/db/*
        sudo rm -rf /home/runner/.cache/*
        df -h

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory "${{ github.workspace }}"
        git config --local pull.rebase true
        git config --local rebase.autoStash true
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          COMMIT_MSG="🤖 Почасовая проверка каталога: $(date '+%Y-%m-%d %H:%M:%S UTC')\n\n$(git status --porcelain | head -20)\nRun ID: ${{ github.run_id }}"
          git commit -m "$COMMIT_MSG"
          # Обновляем удалённую ветку, избегая расхождений
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push origin "HEAD:${GITHUB_REF_NAME}"
        else
          echo "No changes to commit"
        fi

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          data/
          *.log
