name: Manga Monitor

on:
  schedule:
    # Запускаем каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches: [ main ]
    paths:
      - 'config.toml'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build guloader
      run: cargo build --release
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Run manga monitoring
      run: |
        # Создаем директории если их нет
        mkdir -p data downloads scans
        
        # Запускаем мониторинг
        ./target/release/guloader monitor --config config.toml --auto-commit
    
    - name: Commit changes
      run: |
        # Проверяем есть ли изменения
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "🤖 Auto-update: New manga chapters downloaded $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
    
    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          data/
          *.log